# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85f049db9b852ecdd8a6c2166a3a4d03b906fe23b545ea67b7a8415048065b1fa31bd1b28d463acb5681b596dfc65e0106c5cb54123ec544b8a587716872b8bf

test:
  secret_key_base: ada0aedff635f30e4b8b48d98918e4ef203aab8f36eadf97db03c553b12129f35c8099f519d611742c3afb54852f7b3783a6ee4de91fd6fe027b459becc15a2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
